# Use new trusty images, should yield newer compilers and packages
sudo: required
dist: precise
language: cpp

addons:
    apt:
        sources:
            - llvm-toolchain-precise
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
        packages:
            - clang-3.7
            - cmake
            - cmake-data
script:
            - cmake --version
            - mkdir build
            - cd build
            - cmake .. && make
